safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: WWX2016 talk by Alex Hoyau
    # url:  http://example.com/
    company:
        name: CTO @ Secret Media
        # url:  http://example.com/

fork_url: https://github.com/secretmedia/WWX2016-secret-talk
progress: true
line_numbers: true
